### ISSUE TITLE
Old Edge base EdgeHtml - general question.

### ISSUE THREAD

**Issue by seba2282** [nikrolls/uBlock-Edge#130]
Hello,
I have general question. Ublock for Edge is permamently discontinued or will back? 

Best Regards

**Comment by nikrolls** [comment]
Edge itself is being rebuilt on Chromium and will support extensions from the Chrome store. So the Edge-specific version is no longer maintained, due to issues maintaining compatibility with current Edge.

**Comment by seba2282** [comment]
So any plan suport legacy? Chromium final maybe will be after half year or 1 year.

**Comment by nikrolls** [comment]
Likely 6 months. Unfortunately due to issues in Edge's extension support, maintaining compatibility has been extremely challenging. So likely there will be no further updates for the EdgeHTML version.

**Comment by seba2282** [comment]
I see Nano Defender or Adguard is updated, but only Ublock Origin not. @nikrolls, Is ublock origin 1.19.x and are some things (forgot how named) and @jspenguin2017 used that to make next update for EdgeHtml his Nano Adblocker (Ublock Origin Fork with extra filters included). So you can too make. Only ask about patch to @gorhill or @jspenguin2017 :)

**Comment by nikrolls** [comment]
It's also a matter of time. They have time to maintain it, I do not. There have been no volunteers to maintain this extension, instead they forked their own version. This one will not be updated but once Edge on Chromium is released you can use the version that is updated from the Chrome Store. You can even run the Chromium version of Edge now - I use it as my daily driver, it's completely stable.

**Comment by seba2282** [comment]
Maybe you have right. :) I gave you only suggest. But understand you. And sorry if you found bad intencions in my words. :)

**Comment by jspenguin2017** [comment]
> They have time to maintain it, I do not. 

Nope, the way you forked uBO made your port unmaintainable. With my patch driven approach, I spend no longer than 2h every other week to sync upstream changes. 

Look at the amount of code [you rewritten](https://github.com/nikrolls/uBlock-Edge/tree/master/platform/edge) vs. the amount of code [I "rewritten"](https://github.com/NanoAdblocker/NanoCore2/blob/bda7d6e7c55f43c0e6be0aeafd27ffc96b205323/patches/integration/90_0_edgyfy.patch). 

> There have been no volunteers to maintain this extension, instead they forked their own version. 

I have released [Edgyfy](https://github.com/jspenguin2017/Edgyfy/blob/master/edgyfy.js), the shim that makes Nano run on Edge, under a permissive license and I have [notified you](https://github.com/nikrolls/uBlock-Edge/issues/122#issuecomment-421846301) about it. 

No volunteer wants to send PRs because your repo is already beyond redemption. You could have restarted fresh with Edgyfy, it shouldn't take more than an hour or two to get back to where you were.

**Comment by nikrolls** [comment]
I'm not here to argue. I'm not coming to your repository and criticising you. I did it the way existing forks were done at the time, and I don't think many people would blame me for not taking your feedback on board when you approached it in such a superior and unfriendly way.

**Comment by jspenguin2017** [comment]
You criticized me that I rolled my own fork instead of helping you, and that was my response explaining why I chose to not help you. If you feel offended, then I apologize, that was not the intention. I simply wanted to inform you issues with your current setup and how could you make it better so that other volunteers can contribute to it. 

I am not watching your repository, but I got pinged here, I would not have found this thread otherwise. I am certainly not going out of my way to find places to criticize you.

**Comment by seba2282** [comment]
@jspenguin2017, I see, @nikrolls won't help by you, only he went to argued. So I would apologize you for that, I suggested him about he can go help to you and @gorhill. It was mistake. I didn't think, he is on anti. 
@nikrolls, thanks for didn't accept my suggest. We should help all us. It is intention good people from GitHub. They are big friendly family. I agree with words @jspenguin2017. You shouldn't start with argue to him.

**Comment by gdata1** [comment]
Are you planning support for the new edge? Update through the chrome store?

**Comment by seba2282** [comment]
@gdata1, @gorhill supported Edge chromium, but you need add extension from chrome web store of course. Best Regards

**Comment by nikrolls** [comment]
@gdata1 @seba2282 yes, you can do it that way. However @gorhill and I have organised for Microsoft to pull the extension from the Chrome Store to the Edge on Chrome store, so you will have support from Chromium Edge by default without having to enable the Chrome Store.

**Comment by gdata1** [comment]
@nikrolls An older version is installed for chromium edge. If you put through Edge insider addons

**Comment by seba2282** [comment]
@nikrolls, what about old Edge, you seriously claimed support? I want say, to have Edge Chromium by all (not only testers) can be few months.

**Comment by nikrolls** [comment]
@gdata1 Yes, it's two patch versions behind. That can be expected while this process is in beta.

@seba2282 No, old Edge is no longer supported. I was having trouble with the testing being quite time consuming, because while Edge's Web Extension support was good, there were finicky bugs in it that kept cropping up and needed to be worked around. I'm happy to accept, merge and release PRs, but I don't have time to do the debugging and development work myself at this time.

**Comment by gdata1** [comment]
@nikrolls I now can not find the extension in the store Edge Insider

**Comment by nikrolls** [comment]
@gdata1 Hmm, you're right. I'll assume something technical for now, but I'll check back in after a few days to see if it's back and contact Microsoft about it if it's not.

**Comment by gdata1** [comment]
@nikrolls Inform please when will be clear what's the matter

**Comment by nikrolls** [comment]
@gdata1 I'm not sure at the moment, but I'll post back if I find anything out.

**Comment by gorhill** [comment]
@nikrolls Do you know what is the extension scheme on the new Chromium-based Edge? (For example, with Chromium it's `chrome-extension:`, for Firefox it's `moz-extension:`.)

**Comment by nikrolls** [comment]
@gorhill It appears to be `chrome-extension:`, at least for now, for extensions from the Chrome Store and ones, like uB0, which they have automatically pulled into their store from the Chrome Store. It may be different for extensions directly developed for Chromium Edge, but I don't have any of those to check yet (and is likely not relevant for uB0).

**Comment by gdata1** [comment]
@nikrolls The extension did not appear in the Edge Insider store. Is there any news on the subject?

**Comment by gorhill** [comment]
You can download it directly meanwhile: https://microsoftedge.microsoft.com/insider-addons/detail/odfafepnkmbhccpbejgmiehpchacaeak

It just no longer appears as a choice in the main list for blockers.

**Comment by gdata1** [comment]
@gorhill The link you gave appears error downloading. And if I go myself to the store edge insider then I do not see there extension

**Comment by gorhill** [comment]
I don't have Chromium Edge, so I can't check for myself whether it can be downloaded.

**Comment by seba2282** [comment]
@gdata1, you can turn install from other shops and install from chrome web store?

**Comment by gdata1** [comment]
@gorhill I see it again in Microsoft edge insider addons and can install. everything works.

**Comment by ratatoeey** [comment]
its Nov 2019 and Edge HTML is not supported though its the default browser for Windows 10.

from https://www.microsoftedgeinsider.com/en-us/whats-new
>Save the date: Microsoft Edge general availability is expected January 15, 2020

seems its a bit premature to say that default browser is old when new browser hasn't even become generally available yet. and once it does, will take some time to become relevant.

If you don't want to support something just say so, ignore the complainers. Don't elaborate a perfectly good reason. Linux distros frequently throw users out by similar long posts that boil down to-> we don't want to.

so from what I understand, 
- **Edge HTML is not supported by this extension.** last release https://github.com/nikrolls/uBlock-Edge/releases/tag/1.16.6,  was on  Aug 5, 2018. 

- And https://github.com/NanoAdblocker/NanoCore2 supports Edge HTML version and is released frequently, and the developer has a better approach than uBlock-Edge.

I think the README page and project site for https://github.com/nikrolls/uBlock-Edge  should mention https://github.com/nikrolls/uBlock-Edge/issues/130 and its conclusion for Edge HTML support. Hope its not too time-consuming.

----

regards ratatoeey

**Comment by gdata1** [comment]
Hello. why the update in the edge addons store is so lagging behind chrome in edge is still 1.23.0?
