### ISSUE TITLE
Changes to platform-specific code

### ISSUE THREAD

**Issue by gorhill** [nikrolls/uBlock-Edge#20]
Not sure how best this should be handled in the long term, but for now I will just give you a heads-up of the required changes in the platform-specific code for current head:

##### Add `vAPI.shutdown.removeJob` in `vapi-client.js`

Commit: <https://github.com/gorhill/uBlock/commit/c084853d9ad15d57b6c982bb8cf37743f544790a#diff-e56525413093070dcda93114d5869cf8>. This new method is required to be sure the element picker removes itself completely from memory after closing it.

##### Add `self.createSet` in `vapi-client.js`

Commit: <https://github.com/gorhill/uBlock/commit/cd81f866b9cbc9ad670b6cf17e32dfcf26fde8b9>. `self.createSet` should return a sufficiently ES6-compliant Set() object. I guess Edge supports ES6-compliant Set() since the beginning, so adding a simple:

    self.createSet = function() {
        return new Set();
    };

will be enough. Chromium and to a lesser extent Firefox require legacy code to deal with older versions -- moving this to `vapi-client.js` ensures no irrelevant polyfill code ends up in platform-independent `contentscript.js`.

**Comment by nikrolls** [comment]
Thanks -- I'll check this out tonight. I realised I had some global GitHub notification settings turned off so I wasn't getting notified of activity here. I've fixed that now and should be more responsive.

**Comment by nikrolls** [comment]
So currently I've been porting all changes in `platform/chromium/*` to `platform/edge/*`, even ones that are Chromium-specific. So these changes are already in. I've not been that discerning about it, so Edge will have polyfills that it doesn't need (but because they're polyfills they should be dormant). 

I've done this mainly to make the manual porting as easy as possible for now. I'd like to come back and do a cleanup pass, but I'd prefer to be more familiar with the codebase before doing that.
