### ISSUE TITLE
Can't back up settings to file

### ISSUE THREAD

**Issue by stkb** [nikrolls/uBlock-Edge#25]
### Describe the issue
Thematically related to #24 but a slightly different issue. The `Backup to file` button on the "Settings" tab of the settings doesn't do anything when clicked.

### One or more specific URLs where the issue occurs

ms-browser-extension://uBlockOrigin_rfgc05fqypn62/dashboard.html#settings.html

### Steps for anyone to reproduce the issue

1. Install a fresh copy of ublock-edge
2. Go to ublock's settings and the "Settings" tab
3. Click the `Backup to file` button. Nothing happens

### Your settings
- Browser/version: Edge 38.14393.0.0
- uBlock Origin version: 1.9.17b6-edge

Works on the Chrome version

##### Your filter lists

Default

##### Your custom filters (if any)

None

**Comment by nikrolls** [comment]
Thanks @stkb, this was an issue I was aware of but I clearly had forgotten to document it! There are some finicky limitations in generating downloads from a background page in Edge which is the cause of this issue. I will bring it up with Microsoft and if they don't have a workaround then I'm sure they'll add it to their issue tracker.

**Comment by nikrolls** [comment]
There is a fix from Microsoft coming for #24, but I'm not 100% sure that it will fix this issue because there seems to be some extra issues around the fact that this particular download is triggered from a background page. I will let them know about this extra factor and hopefully they can fix it at the same time.
