### ISSUE TITLE
cant isntall from appstore

### ISSUE THREAD

**Issue by 0x000001** [nikrolls/uBlock-Edge#32]
0x80070005

**Comment by wizarrc** [comment]
@0x000001 Just worked fine for me using the Windows Store. I would advise try to install it again after a few hours. That usually solves the issue for me if an app doesn't seem to install without error.

**Comment by nikrolls** [comment]
Thanks @0x000001, I'll keep this ticket open a little while to see if anyone else is having the issue. If you try again now, does it install?

**Comment by gorhill** [comment]
Just in case, some anti-viruses or cleaners will interfere with the installation of uBlock Origin. See <https://github.com/gorhill/uBlock/wiki/Software-known-to-have-uninstalled-uBlock-Origin>.

**Comment by Marsfan** [comment]
@nikrolls @gorhill I recommend that this is closed. I just ran an install for the first time and I encountered no errors.

**Comment by reunicorn** [comment]
@Marsfan @nikrolls @gorhill I think this issue should remain open. It's still failing to install on 2 out of my 4 computers:

- On one of my computers, the extension installed first try and without issues.
- One another computer, the install failed, but after restarting the PC and trying again it succeeded.
- And on the other 2 computers, it failed the first time and every time after that (still failing to install after restarting, clearing Windows Store cache, waiting several days, uninstalling all antiviruses, etc.)

I'm signed in to a different Microsoft account on the PCs that installed successfully and the ones that failed, so that might have something to do with the problem: perhaps it's an issue with the "purchasing" of the app.

**Comment by nikrolls** [comment]
On the one hand, this is an issue that's largely out of our control, at least as it pertains to the source code on this repo. On the other hand, I need to work with Microsoft to see if they can find the issue and fix it. I'm happy to keep it open temporarily while I get them to look into it, but that may be a little while as we approach Christmas. At the very least it would be good to obtain some logs to figure out what may be causing the issue.
