### ISSUE TITLE
Logger shown request was blocked but in fact it wasn't

### ISSUE THREAD

**Issue by tx9191** [nikrolls/uBlock-Edge#75]
Read first: <https://github.com/nikrolls/uBlock-Edge/blob/master/CONTRIBUTING.md>

### Describe the issue
the filter `/tb/_/video_frs_head_` breaks the page on http://tieba.baidu.com/f?ie=utf-8&kw=firefox&fr=search.
I could see in the ublockEdge logger that the requests of http://tb1.bdstatic.com/??/tb/_/tbui/video_player_html5_e8441fb.js,/tb/_/tbui/video_player_fa0bd15.js,/tb/_/video_frs_head_17ecbb0.js and http://tb1.bdstatic.com/??/tb/_/tbui/video_player_0111198.css,/tb/_/video_frs_head_4847a5b.css were blocked, but WireShark shown that the browser did send requests of the later url above to web server.
On Firefox and Chrome that filter just works properly.

### One or more specific URLs where the issue occurs

http://tieba.baidu.com/f?ie=utf-8&kw=firefox&fr=search

### Screenshot in which the issue can be seen

https://imgur.com/a/x8jMZ

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
2. Because we are not looking over your shoulder and
3. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, the issue will be marked as invalid. Lists all settings which differ from default]

- OS/version: Windows 10 x64 1703(Creators Update)
- Browser/version: MS Edge 40.15063.0.0
- uBlock Origin version: 1.12.1

##### Your filter lists
All lists are unchecked except the "My filters" with the only filter in it.

##### Your custom filters (if any)

 `/tb/_/video_frs_head_`

**Comment by tx9191** [comment]
well, I find that adblock plus and adguard have the same porblem, maybe it's caused by browser bugs?

**Comment by nikrolls** [comment]
@tx9191, I'm unable to get uBO to block anything using the custom filter you provided. If I select the video banner you refer to in the element picker, uBO creates a custom filter of `tieba.baidu.com###video_frs_head`, which looks like this:

![image](https://cloud.githubusercontent.com/assets/2626677/25577337/55be4030-2eb9-11e7-98a6-72130dc4fca9.png)

As far as I can tell that looks just like [your Firefox screenshot](https://i.imgur.com/ovpCnxe.png). Are you sure this isn't what you want?

**Comment by nikrolls** [comment]
@scottlow, any thoughts?

In summary:
1. Reset uBO settings
2. Turn off all third-party filters except `My filters`
3. Enter a single filter into `My filters` with the value of `/tb/_/video_frs_head_`
4. Navigate to http://tieba.baidu.com/f?ie=utf-8&kw=firefox&fr=search

You'll notice that both uBO and the console state that a JS file and a CSS file were blocked. However the JS file gets loaded anyway and injects the videos into the page. The CSS file appears to still be blocked which is why the page layout is broken.

I've investigated the code in `traffic.js#onBeforeRequest` and they both successfully return `{cancel: true}`.

**Comment by nikrolls** [comment]
@tx9191 Is this still an issue?

**Comment by nikrolls** [comment]
Closing this due to a lack of activity and being unable to reproduce the issue any longer.
