### ISSUE TITLE
Bring back store compability with W10 version 14.393.0

### ISSUE THREAD

**Issue by xroginhox** [nikrolls/uBlock-Edge#82]
I tried download download the extension in the store for the edge in version 14.393.1198 and it says that it is not compatible with my version and should update to version 15.063 but I did not like this new version of windows and I really like this extension in my opinion Is the best of all. Please release it to anyone who uses this older version of windows in the store if at all possible.

**Comment by target123** [comment]
I can vouch for this as well. Most Windows 10 computers still do not have the Creators Update. With due respect, I cannot see the reason why slightly older versions of Windows 10 would not suffice the requirements of ublock Origin.

**Comment by xt0rted** [comment]
From https://github.com/nikrolls/uBlock-Edge/issues/78#issuecomment-298729665

> uBlock Origin is available on Edge for those running the Windows 10 Creators Update. This is because it relies on features and fixes that are only present in the CU.

**Comment by nikrolls** [comment]
There are many very good reasons that this is not available in the Store for devices that don't have the Creators Update:

* No support for setting sync
* Multiple extensions that monitor traffic do not work together (eg, uBlock and Ghostery): https://github.com/nikrolls/uBlock-Edge/issues/50
* Blocking methods that modify headers trigger the page to download rather than show in browser. This affects very popular sites such as GSM Arena and Tom's Hardware, among many others: https://github.com/nikrolls/uBlock-Edge/issues/45
* Functionality to block media by file size doesn't work: https://github.com/nikrolls/uBlock-Edge/issues/35
* (Possible) Clicking links in Gmail that open in a new tab don't work: https://github.com/nikrolls/uBlock-Edge/issues/2
* Unable to use proper storage for cache files because of a 1MB limit value limit. This meant using IndexedDB which would clear filters every time the browser cache is cleared. Edge has an option to clear the cache on every close which plays havoc with uBlock when using IndexedDB. https://github.com/nikrolls/uBlock-Edge/issues/1
* YouTube scripts fail to initialise on homepage; this means lazy loading and interactivity doesn't work: https://github.com/nikrolls/uBlock-Edge/issues/16
* Exporting settings doesn't work at all: https://github.com/nikrolls/uBlock-Edge/issues/25
* Ads aren't blocked on some sites correctly, for example Bing search: https://github.com/nikrolls/uBlock-Edge/issues/30

You can still download any of the releases from https://github.com/nikrolls/uBlock-Edge/releases and side-load them, however I do not want to make them available to versions of Edge in which they will be broken because that is a recipe for misunderstanding and, to be frank, bad and unfair reviews.

If you have not yet got the Creators Update you can get it from here: https://www.microsoft.com/en-au/software-download/windows10. If your system administrator is not letting you update, you have a right to ask them why not.
