### ISSUE TITLE
Blue banner: Watch YouTube videos with Chrome.

### ISSUE THREAD

**Issue by ZenMasta** [nikrolls/uBlock-Edge#91]
### Describe the issue
While using Microsoft Edge, there is a blue banner at the top of every youtube page that says "Watch YouTube videos with Chrome." The lousy part is that no matter how many times you press the X to ignore the banner, that only matters on the current page so long as you don't refresh. It is visible on every youtube page/video, even if you're already logged in. Since this isn't a traditional ad it would be nice if you would consider figuring out how to prevent this from displaying.

### One or more specific URLs where the issue occurs
http://www.youtube.com

### Screenshot in which the issue can be seen
http://imgur.com/a/sRC7V

### Steps for anyone to reproduce the issue
No particular steps. Just visit youtube while using Microsoft Edge browser.

### Your settings
- OS/version: Windows 10
- Browser/version: Microsoft Edge
- uBlock Origin version: not sure

##### Your filter lists
Default filter lists

**Comment by gorhill** [comment]
Why is this filed as an issue with uBO? You want assistance with a filter, this is not the place for this. Visit <https://www.reddit.com/r/uBlockOrigin/> for support.

**Comment by reunicorn** [comment]
You can permanently remove that banner with the following filter:
`www.youtube.com###ticker`

**Comment by JeffGreenlee42** [comment]
Sorry.. What the HECK does that even mean?   "filter"???   Nowhere in MS Edge do I find any setting with the word "filter"  associated with it!  So what are you referring to?

**Comment by reunicorn** [comment]
You can add a custom filter to uBlock Origin in Edge by doing the following (Note that you first need to [install the uBlock Origin Edge extension](https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4) in order to add custom filters):

1. Open the uBlock dashboard. (Click the "..." menu→ Extensions→ uBlock Origin→ Options)
2. Click on the 3rd tab at the top of the dashboard, titled "My filters"
3. Type or paste the filter you wish to add into the box, then click "Apply changes"
4. The next time you load YouTube (or refresh the page) the filter should take effect and the blue box should disappear.

**Comment by nikrolls** [comment]
Thanks everyone for chiming in. I'm going to close this because it's been answered.
