### ISSUE TITLE
Update the extension...?

### ISSUE THREAD

**Issue by Aerocet** [nikrolls/uBlock-Edge#97]
It's extremely rude to take such a large responsibility as maintaining uBlock Origin on Edge, and then leave it to die after claiming ownership in the Windows Store. Give it to someone who can maintain it.

**Comment by LordManhattan** [comment]
Got an update today. Not sure what changed though.

**Comment by ROCKNROLLKID** [comment]
A lot of the issues/fixes and what not are pretty specific to Chrome/Firefox and thus he doesn't need to include it all in Edge as it will have no effect. I would say that biggest things he needs to do is when a filter gets added/changed/removed/etc or if there is something done backend that would greatly benefit Edge users. I would say that because of this, he could probably get away with only needing to update once a month.

But I realize that your issue was referring to the fact that it was 5 months since last update. He got one up yesterday, like LordManhattan said.

**Comment by Hard-Wired** [comment]
I've been updated to 1.14.23 today! Woot!

**Comment by seba2282** [comment]
I am interesting now, UBO will block ads from TVN adservers or the same, what was before this update (not blocked). Example from https://www.miniminiplus.pl/filmy/pokaz/my-little-pony-duchy . On Firefox Android all time here I have ads. On MS Edge with UBO (PC) I had ads too. And I installed Firefox on PC. But if it fixed, I will back to MS Edge. :)

**Comment by nikrolls** [comment]
@Aerocet You're right, I apologise for my absence. Life events out of my control kept me away. I'm back on the case now.

**Comment by nikrolls** [comment]
@seba2282 I don't quite understand the issue you're describing. If it still occurs with the latest version, please open a ticket and I'll look into it.

**Comment by seba2282** [comment]
@nikrolls, now is ok. Earlier version Ublock didn't block video ads on miniminiplus.pl/filmy. And I saw ads from redcdn tvn adservers (30 seconds videos).
