### ISSUE TITLE
Some characters not shown in ublock setting page on Win 10 insider build

### ISSUE THREAD

**Issue by lychichem** [nikrolls/uBlock-Edge#98]
Read first: <https://github.com/nikrolls/uBlock-Edge/blob/master/CONTRIBUTING.md>

### Describe the issue
After updated Windows 10 to the latest insider slow ring build (17025) and ublock to the latest version (1.14.22), characters in cloud storage setting panel and about panel cannot be shown.

### One or more specific URLs where the issue occurs
The ublock internal page.
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![default](https://user-images.githubusercontent.com/9316590/34039327-02329988-e1ca-11e7-82f8-235bb6862357.PNG)
![1](https://user-images.githubusercontent.com/9316590/34039587-fea40512-e1ca-11e7-8476-3582f31cddb5.PNG)

### Steps for anyone to reproduce the issue
1. Update Windows 10 to build 17025 (insider slow ring).
2. Update ublock origin to 1.14.22
3. Open ublock setting page and go to about panel or rule panel.
### Your settings

[If you fail to provide this info, the issue will be marked as invalid. Lists all settings which differ from default]

- OS/version:  Window 10 insider preview build 17025 64-bit version, system language is Chinese Simplified.
- Browser/version: Edge 41.17025.1000.0
- uBlock Origin version: 1.14.22

##### Your filter lists
No filters
##### Your custom filters (if any)
https://raw.githubusercontent.com/523860169/list/master/ad.txt

Additional info:
This may related to MS released new version of MS YaHei, which is the default UI font for Chinese (Simplified). As a workaround, maybe we can force ublock use another font in setting page.

**Comment by kevin12314** [comment]
Cloud storage setting panel cannot be shown because cloud-ui.js line 93 
`time.toLocaleString('fullwide', timeOptions);` Edge will get error with `'fullwide'` parameter.
make-edge.sh  in GitHub code tool folder has this code `sed -i "s/'fullwide',\s*//g" $DES/js/*.js` is to remove `'fullwide'` parameter.
But I do not know why the release of this version has not been removed.

**Comment by lychichem** [comment]
@kevin12314 so you mean it’s a js parsing error but not a font error?

**Comment by kevin12314** [comment]
@lychichem For cloud storage setting panel ,yes. Now @nikrolls has pushed an update and this new version has fixed this error.

**Comment by lychichem** [comment]
@kevin12314 Okay I've seen ublock origin 1.14.23 fixed the issue partly as you mentioned. So what about the "about" panel? Does it also relates to js parsing error?

**Comment by kevin12314** [comment]
@lychichem I found that because about.html did not reference `<script src="js/vapi.js"></script>`. I found this code is in [src](https://github.com/nikrolls/uBlock-Edge/blob/master/src/about.html) but not in [platform/edge](https://github.com/nikrolls/uBlock-Edge/blob/master/platform/edge/about.html). The released version will give priority to files under platform/edge.

**Comment by nikrolls** [comment]
@kevin12314 This is merged for the next release (working on it presently).
